### ISSUE TITLE
[新功能] 图片集分集，背景图

### ISSUE THREAD

**Issue by JulyGlow** [JulyGlow/tgyz2602#3]
# 图片集
咱们得把图片分下类(像运动会,研学活动),这样找得更快.(在学期里加一个分类,分类里放图片)
图片嘛,对不起咯,我爸妈不让我找老师要,他们说我不务正业,还振振有词,说这事不用我干.目前,我在到处问老师的电话.不到最后,我不放弃.
# 背景图
UI,我觉得还行,但是能不能加个[背景图](https://ts1.cn.mm.bing.net/th/id/R-C.58caba3954a1d0b7c734148c551af2eb?rik=yWuNGGZp0M0J8Q&riu=http%3a%2f%2ffile.xdf.cn%2fuploads%2f200429%2f1092_200429113326hgO1Zj4fcitFOWN4.png&ehk=8xxlzBn5S1MBiglAR%2fFaiZajG7%2fvOL3kO9MMmniO9%2f4%3d&risl=&pid=ImgRaw&r=0)?这样纯色背景很单调.可以参照[天长运动会](https://tzydh.github.io/),他们的渐变就不要了. :)

**Comment by lingbopro** [comment]
这不难，我刚准备写图片预加载

**Comment by Minemetero** [comment]
![image_2024-08-12_183436334](https://github.com/user-attachments/assets/5ac7abf2-ee28-40da-ab72-d7f89a18839b)
等一下星源？
win12的那个？？？

**Comment by Minemetero** [comment]
> # 图片集
> 咱们得把图片分下类(像运动会,研学活动),这样找得更快.(在学期里加一个分类,分类里放图片) 图片嘛,对不起咯,我爸妈不让我找老师要,他们说我不务正业,还振振有词,说这事不用我干.目前,我在到处问老师的电话.不到最后,我不放弃.
> 
> # 背景图
> UI,我觉得还行,但是能不能加个[背景图](https://ts1.cn.mm.bing.net/th/id/R-C.58caba3954a1d0b7c734148c551af2eb?rik=yWuNGGZp0M0J8Q&riu=http%3a%2f%2ffile.xdf.cn%2fuploads%2f200429%2f1092_200429113326hgO1Zj4fcitFOWN4.png&ehk=8xxlzBn5S1MBiglAR%2fFaiZajG7%2fvOL3kO9MMmniO9%2f4%3d&risl=&pid=ImgRaw&r=0)?这样纯色背景很单调.可以参照[天长运动会](https://tzydh.github.io/),他们的渐变就不要了. :)

告诉你爸妈，这叫培养兴趣非常值得支持

**Comment by Minemetero** [comment]
确实这事可能用不到你干，而且我并不觉得会被采用，可是作为一个实践项目，他本身的意义已经远远大于了实际展现出来的东西

**Comment by lingbopro** [comment]
> 确实这事可能用不到你干，而且我并不觉得会被采用，可是作为一个实践项目，你做出来这个东西的过程的意义已经远远大于了实际展现出来的东西

正确的，中肯的

**Comment by lingbopro** [comment]
实在不行我们还可以把这套布局开源成为一个模板

**Comment by lingbopro** [comment]
> ![image_2024-08-12_183436334](https://github.com/user-attachments/assets/5ac7abf2-ee28-40da-ab72-d7f89a18839b)
> 等一下星源？
> win12的那个？？？

是的

**Comment by lingbopro** [comment]
有时候，一件事你做它的过程和意义，以及你从这个过程中学到的东西，比结果重要

**Comment by sjt-2024** [comment]
有道理
但还是想做好

**Comment by lingbopro** [comment]
> 有道理
> 但还是想做好

那当然，毕竟谁不想做好一个自己想做并且爱做的东西呢

嗯…怎么说呢，能搞到最好，不行也没关系，就当是一次经历吧

**Comment by lingbopro** [comment]
不说了，我干代码去了

**Comment by lingbopro** [comment]
图片集搞定

**Comment by sjt-2024** [comment]
> 图片集搞定

@lingbopro 看了你放的图片,我只能说:*是个人才*

**Comment by sjt-2024** [comment]
额?! 背景还没干吗?

**Comment by lingbopro** [comment]
还没，这个图片集的页面滚动还有问题

**Comment by Minemetero** [comment]
Never gonna give u up~~~~~~~~~

**Comment by lingbopro** [comment]
We're no strangers to love
You know the rules and so do I
A full commitment's what I'm thinking of
You wouldn't get this from any other guy
I just wanna tell you how I'm feeling
Gotta make you understand
Never gonna give you up
Never gonna let you down
Never gonna run around and desert you
Never gonna make you cry
Never gonna say goodbye
Never gonna tell a lie and hurt you
We've known each other for so long
Your heart's been aching but you're too shy to say it
Inside we both know what's been going on
We know the game and we're gonna play it
And if you ask me how I'm feeling
Don't tell me you're too blind to see
Never gonna give you up
Never gonna let you down
Never gonna run around and desert you
Never gonna make you cry
Never gonna say goodbye
Never gonna tell a lie and hurt you~

**Comment by Minemetero** [comment]
weeeeeeeeeeeeee

**Comment by Minemetero** [comment]
我跑到MC服务器里唱了一遍结果还有人和我接词！

**Comment by lingbopro** [comment]
> 我跑到MC服务器里唱了一遍结果还有人和我接词！

啊？

**Comment by lingbopro** [comment]
![image](https://github.com/user-attachments/assets/dc446352-ce7b-4b21-a369-cef26eb4e60e)

背景图的话目前只能做成这样，如果要适配顶栏和侧边栏的话比较麻烦

**Comment by sjt-2024** [comment]
@lingbopro 这样够了,感觉模糊点更好(因为我只找到我们几年前的校门图片

**Comment by lingbopro** [comment]
> @lingbopro 这样够了,感觉模糊点更好(因为我只找到我们几年前的校门图片

ok

**Comment by lingbopro** [comment]
背景图是用外部链接还是入库？

**Comment by Minemetero** [comment]
入库

**Comment by sjt-2024** [comment]
外链不能确保稳定

**Comment by Minemetero** [comment]
外部链接指不定哪天挂了就像我们的Github-Hosts

**Comment by lingbopro** [comment]
> 外链不能确保稳定

ok

**Comment by lingbopro** [comment]
这个图1.67M，需不需要压缩（好像没必要

**Comment by lingbopro** [comment]
push了
